# displays token data

GET http://localhost:3000/tests
Authorization: Bearer ... // replace ... with accessToken

### delete old tokens

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "..." // replace ... with old refreshToken
}

### use refresh token

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "..." // replace ... with refreshToken 
}

### create tokens

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Lucas"
}
